ujobs/source/ujobs/apis/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

# --------------------------------
# Author: shenjh@snail.com
# Date: 2015/10/14
# Usage:
# --------------------------------

from django.conf.urls import patterns, url
from views import get_agent_info


urlpatterns = patterns('ujobs.apps.usual.views',
   url(r'^agent_info/(?P<agent_ip>\d+.\d+.\d+.\d+)/$', get_agent_info),

)

ujobs/source/ujobs/apps/files/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

# --------------------------------
# Author: shenjh@snail.com
# Date: 6/5/15
# Usage:
# --------------------------------

from django.conf.urls import patterns, url
from views import *

urlpatterns = patterns('ujobs.apps.files.views',
       url(r'^transfer/(?P<check_id>\d+)/$', send_file),
       url(r'^send_check/$', send_check),
       url(r'^upload/$', upload_file),
       url(r'^remote_file_exists/$', file_exists),
       url(r'^file_exists/$', file_info_exists),
       url(r'^ajax_show_page_detail/(?P<history_step_id>\d+)/$', ajax_show_page_detail),
       url(r'^ajax_show_ip_detail/(?P<history_step_id>\d+)/(?P<ip>.+)/$', ajax_show_ip_detail),
       url(r'^ajax_show_exec_type_detail/(?P<history_step_id>\d+)/(?P<exec_type>.+)/$', ajax_show_exec_type_detail),
)

ujobs/source/ujobs/apps/jobs/urls.py
# -- encoding=utf-8 --

from django.conf.urls import patterns, url
from views import job_list, job_add, job_view, job_delete, job_copy, job_step_edit, job_step_save, full_settings_save, job_start_now, template_job_sync, \
job_add_v2, job_view_v2, job_delete_v2, job_copy_v2, job_start_now_v2

urlpatterns = patterns('ujobs.apps.script.views',
   url(r'^job_list/(?P<template_id>\d+)/$', job_list),
   url(r'^job_add/$', job_add),
   url(r'^job_view/$', job_view),
   url(r'^job_delete/$', job_delete),
   url(r'^job_copy/$', job_copy),
   url(r'^job_start_now/(?P<job_id>\d+)/$', job_start_now),

#   url(r'^job_step/list/(?P<job_id>\d+)/$', job_step_list),
   url(r'^job_step/edit/(?P<job_step_id>\d+)/$', job_step_edit),
   url(r'^job_step/save/(?P<job_step_id>\d+)/$', job_step_save),
   url(r'^save_full_setting/(?P<job_id>\d+)/$', full_settings_save),
   
   url(r'^template_job_sync/$', template_job_sync),
   
   url(r'^job_add_v2/$', job_add_v2),
   url(r'^job_view_v2/$', job_view_v2),
   url(r'^job_delete_v2/$', job_delete_v2),
   url(r'^job_copy_v2/$', job_copy_v2),
   url(r'^job_start_now_v2/(?P<template_id>\d+)/$', job_start_now_v2),
)

ujobs/source/ujobs/urls.py
# -- encoding=utf-8 --
from django.conf.urls import patterns, include, url
from settings import STATIC_ROOT,MEDIA_ROOT
from enums import enum_page
from django.utils.importlib import import_module
from utils.pwd_valid import ajax_agent_valid, ajax_pwd_valid, ajax_pwd_valid_v2, ajax_cmdb_valid, ajax_cmdb_valid_v2

urlpatterns = patterns('',
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': STATIC_ROOT}),
    url(r'^file/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
    url(r'^usual/', include('apps.usual.urls')),
    url(r'^script/', include('apps.script.urls')),
    url(r'^account/', include('apps.accounts.urls')),
    url(r'^files/', include('apps.files.urls')),
    url(r'^md_manage/', include('apps.template.urls')),
    url(r'^job/', include('apps.jobs.urls')),
    url(r'^history/', include('apps.history.urls')),
    url(r'^ajax_agent_valid/$', ajax_agent_valid),
    url(r'^ajax_pwd_valid/(\d+)/$', ajax_pwd_valid),
    url(r'^ajax_pwd_valid_v2/(\d+)/$', ajax_pwd_valid_v2),
    url(r'^ajax_cmdb_valid/$', ajax_cmdb_valid),
    url(r'^ajax_cmdb_valid_v2/$', ajax_cmdb_valid_v2),
    url(r'^api/', include('apis.urls')),
)

for view in enum_page.PAGES:
    v = import_module("page." + view)
    urlpatterns.extend(v.urlpatterns)

ujobs/source/ujobs/apps/files/models.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _
from enums import enum_template
from apps.accounts.models import Account
from audit_log.models.managers import AuditLog

# Create your models here.


class FileInfo(models.Model):
    '''
        上传文件信息
    '''
    def __unicode__(self):
        return self.file_name

    class Meta: #作业
        verbose_name = _('FileInfo')
        verbose_name_plural = _('FileInfo')

    file_name = models.CharField(max_length=255,verbose_name=_(u'文件名'))
    size = models.FloatField(verbose_name=_(u'大小'))
    md5sum = models.CharField(max_length=255, verbose_name=_(u'MD5值'),db_index=True)
    path = models.FilePathField(verbose_name=_(u'文件路径'))
    upload_time = models.DateTimeField(verbose_name=_(u"添加时间"), auto_now_add=True)
    audit_log = AuditLog()

class UploadRecord(models.Model):
    '''
        用户上传记录
    '''
    def __unicode__(self):
        return self.user_name+' upload file '+self.file_name

    user_name = models.CharField(max_length=128,verbose_name=_(u'用户名'))
    fileinfo = models.ForeignKey(FileInfo,verbose_name=_(u'上传文件'))
    file_name = models.CharField(max_length=256,verbose_name=_(u'文件名'))
    upload_time = models.DateTimeField(verbose_name=_(u"上传时间"), auto_now_add=True)
    src_ip = models.IPAddressField(verbose_name=u"上传IP",blank=True,null=True)
    location_type = models.IntegerField(max_length=32,verbose_name=_(u'上传类型'),choices=enum_template.UPLOAD_TYPE_CHOICES,default=enum_template.UPLOAD_TYPE_LOCAL)
    remote_path = models.FilePathField(verbose_name=_(u'远程文件路径'),blank=True,null=True)
    remote_account = models.ForeignKey(Account, verbose_name=_(u'远程账户'), blank=True, null=True)
    audit_log = AuditLog()

ujobs/source/ujobs/apps/history/models.py
#encoding:utf-8

from django.db import models
from django.utils.translation import ugettext_lazy as _
from enums import enum_history, enum_template
from apps.accounts.models import Account
from apps.jobs.models import Job, JobStep, ScheduleJobs
from apps.script.models import Version
from apps.files.models import UploadRecord
from django.contrib.auth.models import User

'''
Created on 2015-5-18

@author: wx
'''

class History(models.Model):
    '''
    @note: 作业历史
    '''
    job = models.ForeignKey(Job, verbose_name=_(u'作业'))
    name = models.CharField(max_length=128, verbose_name=_(u'作业名称'))
    remarks = models.CharField(max_length=256, verbose_name=_(u'备注'), blank=True, null=True)
    mode = models.IntegerField(verbose_name=_(u'执行模式'), choices=enum_template.TEMPLATE_MODE_CHOICES, default=enum_template.TEMPLATE_MODE_AUTO)
    account = models.ForeignKey(Account, verbose_name=_(u'常用账户'), blank=True, null=True)
    target = models.TextField(verbose_name=_(u'目标机器'), blank=True, null=True)
    start_time = models.DateTimeField(verbose_name=_(u"开始时间"), blank=True, null=True)
    end_time = models.DateTimeField(verbose_name=_(u"结束时间"), blank=True, null=True)
    delta_time = models.IntegerField(verbose_name=_(u'总耗时'), blank=True, null=True)
    user = models.ForeignKey(User, verbose_name=_(u'执行人'), related_name='history_create_user', blank=True, null=True)
    status = models.IntegerField(verbose_name=_(u'作业执行状态'), choices=enum_history.HISTORY_STATUS_CHOICES, default=enum_history.STATUS_NOT_START)
    startup_type = models.IntegerField(verbose_name=_(u'作业启动方式'), choices=enum_history.HISTORY_RUN_TYPE_CHOICES, default=enum_history.HISTORY_STARTUP_TYPE_MANUAL)
#    def __unicode__(self):
#        return self.name

    class Meta: #作业历史
        verbose_name = _('History')
        verbose_name_plural = _('Historys')
        
class HistoryStep(models.Model):
    '''
    @note: 步骤历史
    '''
    history = models.ForeignKey(History, verbose_name=_(u'作业历史'))
    jobstep = models.ForeignKey(JobStep, verbose_name=_(u'作业步骤'))
    name = models.CharField(max_length=128, verbose_name=_(u'步骤名称'), blank=True, null=True)
    describe = models.CharField(max_length=256, verbose_name=_(u'步骤描述'), blank=True, null=True,default="")
    order = models.IntegerField(verbose_name=_(u'步骤顺序'), blank=True, null=True)
    is_setting = models.BooleanField(verbose_name=_(u'单独设定'), default=False)
    account = models.ForeignKey(Account, verbose_name=_(u'常用账户'), blank=True, null=True)
    target = models.TextField(verbose_name=_(u'目标机器'), blank=True, null=True)
    start_time = models.DateTimeField(verbose_name=_(u"开始时间"), blank=True, null=True)
    end_time = models.DateTimeField(verbose_name=_(u"结束时间"), blank=True, null=True)
    delta_time = models.IntegerField(verbose_name=_(u'步骤耗时'), blank=True, null=True)
    result = models.IntegerField(verbose_name=_(u'步骤执行结果'), choices=enum_history.HISTORYSTEP_RESULT_CHOICES, default=enum_history.RESULT_NOT_START)
    total_ips = models.TextField(verbose_name=_(u'目标IP'), blank=True, null=True,default=[])
    abnormal_ips = models.TextField(verbose_name=_(u'检测失败IP'), blank=True, null=True,default=[])
    fail_ips = models.TextField(verbose_name=_(u'执行失败IP'), blank=True, null=True,default=[])
    success_ips = models.TextField(verbose_name=_(u'执行成功IP'), blank=True, null=True,default=[])
    
#    def __unicode__(self):
#        return self.name

    class Meta: #步骤历史
        verbose_name = _('HistoryStep')
        verbose_name_plural = _('HistorySteps')

class HistoryStepScript(models.Model):
    '''
    @note: 步骤历史-执行脚本
    '''
    step = models.ForeignKey(HistoryStep, verbose_name=_(u'步骤历史'))
    version = models.ForeignKey(Version, verbose_name=_(u'脚本版本'))
    parameter = models.CharField(max_length=256, verbose_name=_(u'入口参数'), blank=True, null=True)
    timeout = models.IntegerField(verbose_name=_(u'超时时间'), blank=True, null=True)
        
    def __unicode__(self):
        return '%s %s'%(self.step.name, self.version.name)

    class Meta: #步骤历史-执行脚本
        verbose_name = _('HistoryStepScript')
        verbose_name_plural = _('HistoryStepScripts')

class HistoryFileInfo(models.Model):
    """
        每个步骤的文件记录
    """
    step = models.ForeignKey(HistoryStep, verbose_name=_(u'作业步骤'))
    remote_ip = models.CharField(max_length=256, verbose_name=_(u'远程IP'), blank=True, null=True)
    push_account = models.ForeignKey(Account, verbose_name=_(u'远程机器常用账户'), blank=True, null=True)
    location_type = models.IntegerField(max_length=32,verbose_name=_(u'上传类型'),choices=enum_template.UPLOAD_TYPE_CHOICES,default=enum_template.UPLOAD_TYPE_LOCAL)
    remote_path = models.FilePathField(verbose_name=_(u'远程文件路径'),blank=True,null=True)
    record  = models.ForeignKey(UploadRecord, verbose_name=_(u'上传记录'),blank=True,null=True)

class HistoryStepPushFile(models.Model):
    '''
    @note: 步骤历史-分发文件
    '''
    step = models.ForeignKey(HistoryStep, verbose_name=_(u'步骤历史'))
    limit = models.IntegerField(verbose_name=_(u'限速'))
    push_to = models.CharField(max_length=256, verbose_name=_(u'分发至'))
            
    def __unicode__(self):
        return '%s %s'%(self.step.name, self.push_to)

    class Meta: #步骤历史-分发文件
        verbose_name = _('HistoryStepPushFile')
        verbose_name_plural = _('HistoryStepPushFiles')
        
class HistoryStepPullFile(models.Model):
    '''
    @note: 步骤历史-拉取文件
    '''
    step = models.ForeignKey(HistoryStep, verbose_name=_(u'步骤历史'))
    limit = models.IntegerField(verbose_name=_(u'限速'),default=0)
    pull_to = models.CharField(max_length=256, verbose_name=_(u'拉取至'),default="")
    pull_to_ip = models.CharField(max_length=256, verbose_name=_(u'拉取至IP'),default="")
    file_paths = models.TextField(verbose_name=_(u'待拉取文件'), default=[])
            
    def __unicode__(self):
        return '%s %s'%(self.step.name, self.pull_to)

    class Meta: #步骤历史-拉取文件
        verbose_name = _('HistoryStepPullFile')
        verbose_name_plural = _('HistoryStepPullFiles')
        
class HistoryStepText(models.Model):
    '''
    @note: 步骤历史-文本步骤
    '''
    step = models.ForeignKey(HistoryStep, verbose_name=_(u'步骤历史'))
    describe = models.CharField(max_length=256, verbose_name=_(u'文本描述'), blank=True, null=True)
        
    def __unicode__(self):
        return '%s %s'%(self.step.name, self.describe)

    class Meta: #步骤历史-文本步骤
        verbose_name = _('HistoryStepText')
        verbose_name_plural = _('HistoryStepTexts')

class RunningResult(models.Model):
    """
        每个步骤的IP操作列表
    """
    step = models.ForeignKey(HistoryStep, verbose_name=_(u'历史作业步骤'))
    ip = models.CharField(max_length=64,verbose_name=_(u"目标机器IP"), blank=True, null=True,default='*',db_index=True) # use * for all ip
    res_time = models.DateTimeField(verbose_name=_(u"记录时间"), blank=True, null=True,auto_now=True)
    content = models.TextField(verbose_name=_(u"操作内容"), blank=True, null=True)
    progress = models.PositiveIntegerField(verbose_name=_(u'进度'), blank=True, null=True, default=0,db_index=True)


class ScheduleHistory(models.Model):
    """
        自动执行历史
    """
    task = models.ForeignKey(ScheduleJobs, verbose_name=_(u'执行任务'))
    history = models.ForeignKey(History, verbose_name=_(u'执行历史'),blank=True, null=True)
    result = models.IntegerField(max_length=32,verbose_name=_(u'启动结果'),choices=enum_history.SCHEDULE_HISTORY_RESULT_CHOICES,default=enum_history.SCHEDULE_HISTORY_RESULT_FAIL)
    info = models.TextField(verbose_name=_(u"启动信息"), blank=True, null=True,default="")
    trigger_time = models.DateTimeField(verbose_name=_(u"触发时间"), blank=True, null=True,auto_now=True)

    def __unicode__(self):
        return '%s %s'%(self.task.job.name, self.id)

    class Meta:
        verbose_name = _('ScheduleHistory')
        verbose_name_plural = _('ScheduleHistory')

ujobs/source/ujobs/apps/salts/models.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

#--------------------------------
# Author: shenjh@snail.com
# Date: 2015-05-20
# Usage:
#--------------------------------

from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.

class SaltJob(models.Model):
    '''
        store salt job commands.
    '''
    jid = models.CharField(max_length=255, verbose_name=_('Job id'))
    ctime = models.DateTimeField(verbose_name=_('Send Time'), auto_now_add=True)
    load = models.TextField(verbose_name=_('Command content'))

    class Meta:
        db_table = 'jids'
        verbose_name = _('Salt Job')
        verbose_name_plural = _('Salt Job')


class SaltReturn(models.Model):
    '''
        store salt job results.
    '''
    fun = models.CharField(max_length=255, verbose_name=_('Job Command'), blank=True, null=True)
    jid = models.CharField(max_length=255, verbose_name=_('Job Id'))
    minion_id = models.CharField(max_length=255, verbose_name=_('Minion Id'))
    success = models.CharField(max_length=10, verbose_name=_('Is Success'), blank=True, null=True, )
    ctime = models.DateTimeField(verbose_name=_('Receive Time'), auto_now_add=True)
    result = models.TextField(verbose_name=_('Return Content'))
    full_result = models.TextField(verbose_name=_('Full Return'))

    class Meta:
        db_table = 'salt_returns'
        verbose_name = _('Salt Return')
        verbose_name_plural = _('Salt Return')

ujobs/source/ujobs/apps/usual/models.py
from django.db import models

# Create your models here.

ujobs/source/ujobs/apps/accounts/forms.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
'''
Created on 2015-5-22

@author: wx
'''

from django import forms
#from django.core.exceptions import ValidationError
from models import Account

class AccountForm(forms.ModelForm):
    name = forms.CharField(error_messages={'required': u'请输入账户名称', 'unique': u'执行帐号名称已存在，请重新输入'})
    name_abbr = forms.CharField(error_messages={'required': u'请输入账户别名'})
    password = forms.CharField(widget=forms.PasswordInput, error_messages={'required': u'请输入账户密码'})
    
    class Meta:
        model = Account

ujobs/source/ujobs/apps/history/forms.py
# -- encoding=utf-8 --
from django import forms

ujobs/source/ujobs/apps/jobs/forms.py
# -- encoding=utf-8 --
from django import forms

ujobs/source/ujobs/apps/script/forms.py
# -- encoding=utf-8 --
from django import forms

ujobs/source/ujobs/apis/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

# --------------------------------
# Author: shenjh@snail.com
# Date: 2015/10/14
# Usage:
# --------------------------------

import os, sys
sys.path.insert(0, os.path.abspath(os.curdir))
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from utils.redisclient import rc
from releaseinfo import DETAIL_KEY_PREFIX,IP_KEY_PREFIX
import traceback
import json
import logging


logger = logging.getLogger('logger_api')

@csrf_exempt
def get_agent_info(request,agent_ip):
    """
        get agent info from ip.
    """
    info = {}
    logger.debug("#### start api request call: api/get_agent_info/, IP:{0}".format(agent_ip))
    keys = ['biosversion', 'kernel', 'domain', 'kernelrelease', 'serialnumber', 'mem_total', 'SSDs', 'osrelease', 'ip6_interfaces', 'num_cpus', 'hwaddr_interfaces', 'ip4_interfaces', 'cpu_model', 'biosreleasedate', 'host', 'gpus', 'manufacturer', 'num_gpus', 'virtual', 'productname', 'osarch', 'cpuarch', 'os']
    try:
        minion_id = rc.get(IP_KEY_PREFIX+agent_ip)
        if minion_id:
            values = rc.hmget(DETAIL_KEY_PREFIX+minion_id,keys)
            json_values = []
            for value in values:
                try:
                    json_values.append(eval(value))
                except:
                    json_values.append(value)
            info =  dict(zip(keys, json_values))
    except Exception,e:
        error = traceback.format_exc()
        print error
        logger.error(error)
    logger.debug("#### api request end!")
    return HttpResponse(json.dumps(info), content_type="application/json")

ujobs/source/ujobs/apps/salts/views.py
from django.shortcuts import render

# Create your views here.

ujobs/source/ujobs/templates/history/file_view.html
<!-- 分发文件步骤设置项 -->
<legend style="font-size:14px"><span class="caret-arrow-up"></span>步骤设置</legend>
<form id="sendfile_view_form_{{ history_step.id }}" action="javascript:void(0);" method="post" class="form-horizontal">{% csrf_token %}
	<div class="control-group">
		<label class="control-label muted">步骤名称：<span class="red">*</span></label>
		<div class="controls">
			<input type="text" disabled value="{{ history_step.jobstep.name }}">
		</div>			  
	</div>
	<div class="control-group">
		<label class="control-label muted">步骤描述：<span class="red">*</span></label>
		<div class="controls">
			<textarea style="width:420px;" disabled>{{ history_step.jobstep.template_step.describe }}</textarea>
		</div>		  
	</div>
	<div class="control-group hide">
		<label class="control-label muted">限速：<span class="red">*</span></label>
		<div class="controls">
			<input type="text" value="{{ history_step_push_file.limit }}" />
		</div>			  
	</div>
	<div class="control-group">
		<label class="control-label muted">待分发文件：<span class="red">*</span></label>
		<div class="controls">
			<b></b>
			<ul id="file-show2" class="ip-style">
                {% for fileinfo in history_file_infos %}
                    <li class='clearfix list2'>{{ fileinfo.get_location_type_display }}：<i class='file-road' style="width: auto;">{{ fileinfo.remote_path }}</i><i class='ipconfig'  style="width: auto;">{{ fileinfo.remote_ip }}</i><i class='server-account'></i></li>
                {% endfor %}
			</ul>
		</div>  
	</div>
	<div class="control-group">
		<label class="control-label muted">分发路径：<span class="red">*</span></label>
		<div class="controls">
			<input type="text" placeholder="请填写分发的路径" value="{{ history_step_push_file.push_to }}" disabled>
		</div>  
	</div>
	<div class="control-group" >
		<div class="controls">
			<input class="sendfile-view-toggle" style="margin-top: 8px;" type="checkbox" {% if history_step.is_setting == 1 %}checked{% endif %} disabled>
			<label style="display:inline-block;">本步骤使用如下目标机器取代全程目标机器</label>
		</div>
	</div>
	<div class="control-group target-view hide">
		<label class="control-label muted">目标机器：</label>
		<div class="controls">
			<ul class="ip-style">
                <li class="clearfix">
                    {% for ip in targets %}
                        <i class="ipconfig">{{ ip }}</i>
                    {% endfor %}
                </li>
			</ul>
		</div>
	</div>
</form>
<script>
	// 按钮样式
   	icheck($('#sendfile_view_form_{{history_step.id}} input:checkbox'));

	if($(".sendfile-view-toggle").prop("checked")){
		$(".target-view").removeClass("hide");
	}
</script>

ujobs/source/ujobs/templates/history/job_info.html
{% load ujobs %}
<!-- 查看实例 -->
<div class="row-fluid">
    <form id="myform" action="javascript:void(0);" method="post" class="form-horizontal myform">{% csrf_token %}
        <div class="control-group">
            <label class="control-label muted">作业名称：</label>
            <span class="control-label txtlf">{{ job_name }}</span>
            <label class="control-label muted">开发商：</label>
            <span class="control-label txtlf">{{ history.create_user|default:history.job.create_user }}</span>
            <label class="control-label muted">作业类型：</label>
            <span class="control-label txtlf">{{ template_type }}</span>
            <label class="control-label muted">所属业务：</label>
            <span class="control-label txtlf">{{ history.job.template.work_type | default_if_none:"无" }}</span>
        </div>
        <div class="control-group">
            <label class="control-label muted">备注：</label>
            <span class="control-label txtlf">{{ history.remarks|default:""}}</span>
        </div>
        <table class="table table-striped table-bordered table-hover" id="job_info_example">
            <thead>
            <tr>
                <th width=25%>执行顺序</th>
                <th width=25%>步骤名</th>
                <th width=25%>步骤类型</th>
                <th width=25%>目标机器（检测失败/总）</th>
            </tr>
            </thead>
            <tbody>
            {% for step in history_steps %}
                <tr onclick="show_history_step_info('{{ step.id }}', '{{ history.id }}')">
                    <td>第{{ forloop.counter }}步</td>
                    <td>{{ step.name|default:step.jobstep.name }}</td>
                    <td>{{ step.jobstep.get_step_type_display }}</td>
                    <td>{{ step.abnormal_ips|get_ips_length }}/{{ step.total_ips|get_ips_length }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <fieldset>
            <legend style="font-size:14px"><span class="caret-arrow-up"></span>全程设置</legend>
            <div class="control-group" style="margin-top:0;">
                <label class="control-label muted">执行模式：</label>
                <span class="control-label txtlf">{{ history.get_mode_display|default:"无人模式" }}</span>
            </div>
            <div class="control-group">
                <label class="control-label muted">目标机器：</label>
                <span class="control-label target-txt txtlf">{{ overall_target|default:"" }}</span>
            </div>
            <div class="control-group hide">
                <label class="control-label muted">常用账户：</label>
                <div class="controls">
                    <select style="width: 359px;">

                    </select>
                </div>
            </div>
        </fieldset>
        <fieldset id="history_step_info_{{ history.id }}">
            <legend style="font-size:14px"><span class="caret-arrow-down"></span>步骤设置</legend>
            <div>请点击一个步骤名查看</div>
        </fieldset>
    </form>
</div>
<script>
$(function () {
   /*$('#job_info_example').dataTable({
    	"sDom": 'lfrtip',
    	 "bLengthChange":false,
    	 "iDisplayLength":10,
    	 "aoColumnDefs": [{ "bSortable": false, "aTargets": [0,1,2,3] }],
         "bProcessing": false,
         "bServerSide": false,
         "sPaginationType": "full_numbers",
         "bFilter":false,
         "bPaginate": false,
    	 "bInfo": false,
    	 "bSearchable": false,
         "bRetrieve ": true,
         "bDestroy":true,
    	 "oLanguage":{
    	 	   "sUrl":'/static/tool_js/data_table/cn/jquery.dataTable.cn.txt'
         }
    });*/
});
</script>

ujobs/source/ujobs/templates/history/text_detail.html
<!-- 文本步骤详情 -->
<div class="row-fluid">
	<form class="form-horizontal">
		<div class="control-group" style="margin-left:28px;">
            <h4>{{ job_name }}</h4>
        </div>
        <div class="control-group">
        	<label class="control-label muted">执行人：</label>
        	<span class="control-label txtlf">{{ history.user.username }}</span>
        </div>
        <div class="control-group">
        	<label class="control-label muted">开始时间：</label>
        	<span class="control-label txtlf">{{ start_time }}</span>
        </div>
        <div class="control-group">
        	<label class="control-label muted">结束时间：</label>
        	<span class="control-label txtlf">{{ end_time }}</span>
        </div>
        <div class="control-group">
        	<label class="control-label muted">总耗时(s)：</label>
        	<span class="control-label txtlf">0</span>
        </div>
        <div class="control-group" style="margin-left:25px;">
			<textarea style="width:380px;height:150px;">{{ history_step.describe }}</textarea>
        </div>
	</form>
</div>

ujobs/source/ujobs/templates/history/text_view.html
<!-- 文本步骤设置项 -->
<legend style="font-size:14px"><span class="caret-arrow-up"></span>步骤设置</legend>
<form class="form-horizontal">{% csrf_token %}
	<div class="control-group">
		<label class="control-label muted">步骤名称：<span class="red">*</span></label>
		<div class="controls">
			<input type="text" disabled value="{{ history_step_text.step.name }}">
		</div>
	</div>
	<div class="control-group">
		<label class="control-label muted">文本描述：<span class="red">*</span></label>
		<div class="controls">
			<textarea placeholder="请输入文本描述" style="width:420px;height:70px;" disabled>{{ history_step_text.describe }}</textarea>
		</div>
	</div>
</form>