ujobs/source/ujobs/apis/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

# --------------------------------
# Author: shenjh@snail.com
# Date: 2015/10/14
# Usage:
# --------------------------------

from django.conf.urls import patterns, url
from views import get_agent_info


urlpatterns = patterns('ujobs.apps.usual.views',
   url(r'^agent_info/(?P<agent_ip>\d+.\d+.\d+.\d+)/$', get_agent_info),

)

ujobs/source/ujobs/apps/files/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

# --------------------------------
# Author: shenjh@snail.com
# Date: 6/5/15
# Usage:
# --------------------------------

from django.conf.urls import patterns, url
from views import *

urlpatterns = patterns('ujobs.apps.files.views',
       url(r'^transfer/(?P<check_id>\d+)/$', send_file),
       url(r'^send_check/$', send_check),
       url(r'^upload/$', upload_file),
       url(r'^remote_file_exists/$', file_exists),
       url(r'^file_exists/$', file_info_exists),
       url(r'^ajax_show_page_detail/(?P<history_step_id>\d+)/$', ajax_show_page_detail),
       url(r'^ajax_show_ip_detail/(?P<history_step_id>\d+)/(?P<ip>.+)/$', ajax_show_ip_detail),
       url(r'^ajax_show_exec_type_detail/(?P<history_step_id>\d+)/(?P<exec_type>.+)/$', ajax_show_exec_type_detail),
)

ujobs/source/ujobs/apps/jobs/urls.py
# -- encoding=utf-8 --

from django.conf.urls import patterns, url
from views import job_list, job_add, job_view, job_delete, job_copy, job_step_edit, job_step_save, full_settings_save, job_start_now, template_job_sync, \
job_add_v2, job_view_v2, job_delete_v2, job_copy_v2, job_start_now_v2

urlpatterns = patterns('ujobs.apps.script.views',
   url(r'^job_list/(?P<template_id>\d+)/$', job_list),
   url(r'^job_add/$', job_add),
   url(r'^job_view/$', job_view),
   url(r'^job_delete/$', job_delete),
   url(r'^job_copy/$', job_copy),
   url(r'^job_start_now/(?P<job_id>\d+)/$', job_start_now),

#   url(r'^job_step/list/(?P<job_id>\d+)/$', job_step_list),
   url(r'^job_step/edit/(?P<job_step_id>\d+)/$', job_step_edit),
   url(r'^job_step/save/(?P<job_step_id>\d+)/$', job_step_save),
   url(r'^save_full_setting/(?P<job_id>\d+)/$', full_settings_save),
   
   url(r'^template_job_sync/$', template_job_sync),
   
   url(r'^job_add_v2/$', job_add_v2),
   url(r'^job_view_v2/$', job_view_v2),
   url(r'^job_delete_v2/$', job_delete_v2),
   url(r'^job_copy_v2/$', job_copy_v2),
   url(r'^job_start_now_v2/(?P<template_id>\d+)/$', job_start_now_v2),
)

ujobs/source/ujobs/urls.py
# -- encoding=utf-8 --
from django.conf.urls import patterns, include, url
from settings import STATIC_ROOT,MEDIA_ROOT
from enums import enum_page
from django.utils.importlib import import_module
from utils.pwd_valid import ajax_agent_valid, ajax_pwd_valid, ajax_pwd_valid_v2, ajax_cmdb_valid, ajax_cmdb_valid_v2

urlpatterns = patterns('',
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': STATIC_ROOT}),
    url(r'^file/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
    url(r'^usual/', include('apps.usual.urls')),
    url(r'^script/', include('apps.script.urls')),
    url(r'^account/', include('apps.accounts.urls')),
    url(r'^files/', include('apps.files.urls')),
    url(r'^md_manage/', include('apps.template.urls')),
    url(r'^job/', include('apps.jobs.urls')),
    url(r'^history/', include('apps.history.urls')),
    url(r'^ajax_agent_valid/$', ajax_agent_valid),
    url(r'^ajax_pwd_valid/(\d+)/$', ajax_pwd_valid),
    url(r'^ajax_pwd_valid_v2/(\d+)/$', ajax_pwd_valid_v2),
    url(r'^ajax_cmdb_valid/$', ajax_cmdb_valid),
    url(r'^ajax_cmdb_valid_v2/$', ajax_cmdb_valid_v2),
    url(r'^api/', include('apis.urls')),
)

for view in enum_page.PAGES:
    v = import_module("page." + view)
    urlpatterns.extend(v.urlpatterns)

ujobs/source/ujobs/apps/files/models.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _
from enums import enum_template
from apps.accounts.models import Account
from audit_log.models.managers import AuditLog

# Create your models here.


class FileInfo(models.Model):
    '''
        上传文件信息
    '''
    def __unicode__(self):
        return self.file_name

    class Meta: #作业
        verbose_name = _('FileInfo')
        verbose_name_plural = _('FileInfo')

    file_name = models.CharField(max_length=255,verbose_name=_(u'文件名'))
    size = models.FloatField(verbose_name=_(u'大小'))
    md5sum = models.CharField(max_length=255, verbose_name=_(u'MD5值'),db_index=True)
    path = models.FilePathField(verbose_name=_(u'文件路径'))
    upload_time = models.DateTimeField(verbose_name=_(u"添加时间"), auto_now_add=True)
    audit_log = AuditLog()

class UploadRecord(models.Model):
    '''
        用户上传记录
    '''
    def __unicode__(self):
        return self.user_name+' upload file '+self.file_name

    user_name = models.CharField(max_length=128,verbose_name=_(u'用户名'))
    fileinfo = models.ForeignKey(FileInfo,verbose_name=_(u'上传文件'))
    file_name = models.CharField(max_length=256,verbose_name=_(u'文件名'))
    upload_time = models.DateTimeField(verbose_name=_(u"上传时间"), auto_now_add=True)
    src_ip = models.IPAddressField(verbose_name=u"上传IP",blank=True,null=True)
    location_type = models.IntegerField(max_length=32,verbose_name=_(u'上传类型'),choices=enum_template.UPLOAD_TYPE_CHOICES,default=enum_template.UPLOAD_TYPE_LOCAL)
    remote_path = models.FilePathField(verbose_name=_(u'远程文件路径'),blank=True,null=True)
    remote_account = models.ForeignKey(Account, verbose_name=_(u'远程账户'), blank=True, null=True)
    audit_log = AuditLog()

ujobs/source/ujobs/apps/template/models.py
#encoding:utf-8

from django.db import models
from django.utils.translation import ugettext_lazy as _
from enums import enum_template
from apps.accounts.models import Account
from apps.script.models import Version
from audit_log.models.managers import AuditLog
from django.contrib.auth.models import User
from apps.files.models import UploadRecord

'''
Created on 2015-5-14

@author: wx
'''

class Template(models.Model): 
    '''
    @note: 模板
    '''
    name = models.CharField(max_length=128, verbose_name=_(u'模板名称'), blank=True, null=True)
    template_type = models.IntegerField(verbose_name=_(u'模板类型'), choices=enum_template.TEMPLATE_TYPE_CHOICES, default=enum_template.TEMPLATE_TYPE0)
    work_type = models.CharField(max_length=256, verbose_name=_(u'业务类型'), blank=True, null=True)
    remarks = models.CharField(max_length=256, verbose_name=_(u'备注'), blank=True, null=True)
    create_user = models.ForeignKey(User, verbose_name=_(u'创建人'), related_name='template_create_user', blank=True, null=True)
#    create_user = models.CharField(max_length=256, verbose_name=_(u'创建人'), blank=True, null=True)
    update_user = models.ForeignKey(User, verbose_name=_(u'更新人'), related_name='template_update_user', blank=True, null=True)
#    update_user = models.CharField(max_length=256, verbose_name=_(u'更新人'), blank=True, null=True)
    created = models.DateTimeField(verbose_name=_(u"创建时间"), auto_now_add=True)
    updated = models.DateTimeField(verbose_name=_(u"更新时间"), auto_now=True)
    mode = models.IntegerField(verbose_name=_(u'执行模式'), choices=enum_template.TEMPLATE_MODE_CHOICES, default=enum_template.TEMPLATE_MODE_MANNUAL, blank=True, null=True)
    account = models.ForeignKey(Account, verbose_name=_(u'常用账户'), blank=True, null=True)
    target = models.TextField(verbose_name=_(u'目标机器'), blank=True, null=True)
    is_delete = models.BooleanField(verbose_name=_(u'是否删除'), default=False)
    audit_log = AuditLog()

    def __unicode__(self):
        return self.name
    

    class Meta: #模板
        verbose_name = _('Template')
        verbose_name_plural = _('Templates')
        
class TemplateStep(models.Model):
    '''
    @note: 模板步骤
    '''
    template = models.ForeignKey(Template, verbose_name=_(u'模板'))
    name = models.CharField(max_length=128, verbose_name=_(u'步骤名称'), blank=True, null=True)
    describe = models.CharField(max_length=256, verbose_name=_(u'步骤描述'), blank=True, null=True,default="")
    step_type = models.IntegerField(verbose_name=_(u'步骤类型'), choices=enum_template.STEP_TYPE_CHOICES, default=enum_template.STEP_TYPE_SCRIPT)
    order = models.IntegerField(verbose_name=_(u'步骤顺序'), blank=True, null=True)
    is_setting = models.BooleanField(verbose_name=_(u'单独设定'), default=False)
    account = models.ForeignKey(Account, verbose_name=_(u'常用账户'), blank=True, null=True)
    target = models.TextField(verbose_name=_(u'目标机器'), blank=True, null=True)
    is_checked = models.BooleanField(verbose_name=_(u'是否勾选'), default=True)
    is_delete = models.BooleanField(verbose_name=_(u'是否删除'), default=False)
    audit_log = AuditLog()

    def __unicode__(self):
        return self.name

    class Meta: #模板步骤
        verbose_name = _('TemplateStep')
        verbose_name_plural = _('TemplateSteps')

class TemplateStepScript(models.Model):
    '''
    @note: 模板步骤-执行脚本
    '''
    step = models.ForeignKey(TemplateStep, verbose_name=_(u'模板步骤'))
    version = models.ForeignKey(Version, verbose_name=_(u'脚本版本'), blank=True, null=True)
    parameter = models.CharField(max_length=256, verbose_name=_(u'入口参数'), blank=True, null=True,default="")
    timeout = models.IntegerField(verbose_name=_(u'超时时间'), blank=True, null=True,default=0)
    audit_log = AuditLog()

    def __unicode__(self):
        return '%s %s'%(self.step.name, self.version.name)

    class Meta: #模板步骤-执行脚本
        verbose_name = _('TemplateStepScript')
        verbose_name_plural = _('TemplateStepScripts')


class TemplateFileInfo(models.Model):
    """
        分发,拉取文件的文件信息
    """
    step = models.ForeignKey(TemplateStep, verbose_name=_(u'模板步骤'))
    remote_ip = models.CharField(max_length=256, verbose_name=_(u'远程IP'), blank=True, null=True)
    push_account = models.ForeignKey(Account, verbose_name=_(u'远程机器常用账户'), blank=True, null=True)
    location_type = models.IntegerField(max_length=32,verbose_name=_(u'上传类型'),choices=enum_template.UPLOAD_TYPE_CHOICES,default=enum_template.UPLOAD_TYPE_LOCAL)
    remote_path = models.FilePathField(verbose_name=_(u'远程文件路径'),blank=True,null=True)
    record  = models.ForeignKey(UploadRecord, verbose_name=_(u'上传记录'),blank=True,null=True)
    audit_log = AuditLog()

class TemplateStepPushFile(models.Model):
    '''
    @note: 模板步骤-分发文件
    '''
    step = models.ForeignKey(TemplateStep, verbose_name=_(u'模板步骤'))
    limit = models.IntegerField(verbose_name=_(u'限速'),default=0)
    push_to = models.CharField(max_length=256, verbose_name=_(u'分发至'),default="")
    audit_log = AuditLog()
    
    def __unicode__(self):
        return '%s %s'%(self.step.name, self.push_to)

    class Meta: #模板步骤-分发文件
        verbose_name = _('TemplateStepPushFile')
        verbose_name_plural = _('TemplateStepPushFiles')

class TemplateStepPullFile(models.Model):
    '''
    @note: 模板步骤-拉取文件
    '''
    step = models.ForeignKey(TemplateStep, verbose_name=_(u'模板步骤'))
    limit = models.IntegerField(verbose_name=_(u'限速'),default=0)
    pull_to = models.CharField(max_length=256, verbose_name=_(u'拉取至'),default="")
    pull_to_ip = models.CharField(max_length=256, verbose_name=_(u'拉取至IP'),default="")
    file_paths = models.TextField(verbose_name=_(u'待拉取文件'), default=[])
    audit_log = AuditLog()
    
    def __unicode__(self):
        return '%s %s'%(self.step.name, self.pull_to)

    class Meta: #模板步骤-拉取文件
        verbose_name = _('TemplateStepPullFile')
        verbose_name_plural = _('TemplateStepPullFiles')
        
class TemplateStepText(models.Model):
    '''
    @note: 模板步骤-文本步骤
    '''
    step = models.ForeignKey(TemplateStep, verbose_name=_(u'模板步骤'))
    describe = models.CharField(max_length=256, verbose_name=_(u'文本描述'), default="")
    audit_log = AuditLog()
    
    def __unicode__(self):
        return '%s %s'%(self.step.name, self.describe)

    class Meta: #模板步骤-文本步骤
        verbose_name = _('TemplateStepText')
        verbose_name_plural = _('TemplateStepTexts')

ujobs/source/ujobs/apps/usual/models.py
from django.db import models

# Create your models here.

ujobs/source/ujobs/apps/accounts/forms.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
'''
Created on 2015-5-22

@author: wx
'''

from django import forms
#from django.core.exceptions import ValidationError
from models import Account

class AccountForm(forms.ModelForm):
    name = forms.CharField(error_messages={'required': u'请输入账户名称', 'unique': u'执行帐号名称已存在，请重新输入'})
    name_abbr = forms.CharField(error_messages={'required': u'请输入账户别名'})
    password = forms.CharField(widget=forms.PasswordInput, error_messages={'required': u'请输入账户密码'})
    
    class Meta:
        model = Account

ujobs/source/ujobs/apps/history/forms.py
# -- encoding=utf-8 --
from django import forms

ujobs/source/ujobs/apps/jobs/forms.py
# -- encoding=utf-8 --
from django import forms

ujobs/source/ujobs/apps/script/forms.py
# -- encoding=utf-8 --
from django import forms

ujobs/source/ujobs/apps/template/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# --------------------------------
# Author: shenjh@snail.com
# Date: 2015/8/4
# Usage:
# --------------------------------

from django import forms
from models import Template
from enums import enum_template

class AddTemplateForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': u"请填写作业名称，例如，版本发布，更新等",'style':"width:670px;"}),error_messages={'required': u'请输入作业名称'})
    template_type = forms.ChoiceField(choices=enum_template.USER_TEMPLATE_TYPES,error_messages={'required': u'请输入作业类型'})
    remarks = forms.CharField(widget=forms.Textarea(attrs={'placeholder': u"请输入作业备注",'rows':'4','class':'txtstyle','style':"width:670px;"}),error_messages={'required': u'请输入备注描述'})

    def __init__(self, *args, **kwargs):
        self._user = kwargs.pop('user',None)
        super(AddTemplateForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Template
        fields = ['name','template_type','remarks']

    def clean_name(self):
        name = self.cleaned_data.get("name")
        try:
            Template.objects.get(name=name,create_user=self._user,is_delete=False)
            raise forms.ValidationError(u"您已经创建了该名称的模板")
        except Template.MultipleObjectsReturned:
            raise forms.ValidationError(u"当前用户存在多个同名模板")
        except Template.DoesNotExist:
            pass
        return name

class EditTemplateForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': u"请填写作业名称，例如，版本发布，更新等",'style':"width:670px;"}),error_messages={'required': u'请输入作业名称', 'unique': u'作业名称已存在，请重新输入'})
    template_type = forms.ChoiceField(widget=forms.Select(attrs={'style':'width:684px;'}),choices=enum_template.USER_TEMPLATE_TYPES,error_messages={'required': u'请输入作业类型'})
    remarks = forms.CharField(widget=forms.Textarea(attrs={'placeholder': u"请输入作业备注",'rows':'4','class':'txtstyle','style':"width:670px;"}),error_messages={'required': u'请输入备注描述'})

    class Meta:
        model = Template
        fields = ['name','template_type','remarks']

    def __init__(self, *args, **kwargs):
        self._user = kwargs.pop('user',None)
        super(EditTemplateForm, self).__init__(*args, **kwargs)

    def clean_name(self):
        name = self.cleaned_data.get("name")
        try:
            if 'name' in self.changed_data:
                templates = Template.objects.filter(name=name,create_user=self._user,is_delete=False)
                if templates.count()>0:
                    raise forms.ValidationError(u"您已经创建了该名称的模板")
        except Template.DoesNotExist:
            pass
        return name

ujobs/source/ujobs/apis/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

# --------------------------------
# Author: shenjh@snail.com
# Date: 2015/10/14
# Usage:
# --------------------------------

import os, sys
sys.path.insert(0, os.path.abspath(os.curdir))
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from utils.redisclient import rc
from releaseinfo import DETAIL_KEY_PREFIX,IP_KEY_PREFIX
import traceback
import json
import logging


logger = logging.getLogger('logger_api')

@csrf_exempt
def get_agent_info(request,agent_ip):
    """
        get agent info from ip.
    """
    info = {}
    logger.debug("#### start api request call: api/get_agent_info/, IP:{0}".format(agent_ip))
    keys = ['biosversion', 'kernel', 'domain', 'kernelrelease', 'serialnumber', 'mem_total', 'SSDs', 'osrelease', 'ip6_interfaces', 'num_cpus', 'hwaddr_interfaces', 'ip4_interfaces', 'cpu_model', 'biosreleasedate', 'host', 'gpus', 'manufacturer', 'num_gpus', 'virtual', 'productname', 'osarch', 'cpuarch', 'os']
    try:
        minion_id = rc.get(IP_KEY_PREFIX+agent_ip)
        if minion_id:
            values = rc.hmget(DETAIL_KEY_PREFIX+minion_id,keys)
            json_values = []
            for value in values:
                try:
                    json_values.append(eval(value))
                except:
                    json_values.append(value)
            info =  dict(zip(keys, json_values))
    except Exception,e:
        error = traceback.format_exc()
        print error
        logger.error(error)
    logger.debug("#### api request end!")
    return HttpResponse(json.dumps(info), content_type="application/json")

ujobs/source/ujobs/apps/salts/views.py
from django.shortcuts import render

# Create your views here.

ujobs/source/ujobs/templates/md_manage/edit_text.html
<!-- 编辑作业（文本步骤）--> 
<div class="row-fluid edit-text-wrap">
	<form id="edit_template_step_form_{{ step.id }}" class="form-horizontal">{% csrf_token %}
		<div class="control-group">
			<label class="control-label muted">步骤名称：<span class="red">*</span></label>
			<div class="controls">
				<input id="step_name" class="edit-text-name" name="step_name" type="text" placeholder="请输入步骤名称" value='{{ step.name }}'>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label muted">文本描述：<span class="red">*</span></label>
			<div class="controls">
				<textarea id="step_description" name="step_description" class="txtstyle edit-text-content" placeholder="请输入文本描述">{{ sub_step.describe }}</textarea>
			</div>		  
		</div>
		<br>
		<div class="control-group">
			<div class="controls">
				<button class="btn btn-primary" data-type="text" onclick="handle_edit_template_step({{ step.id }},{{ step.template.id }},true,this,false);return false;">
					<i class="icon-ok icon-white"></i>
					保存步骤
				</button>
				<button class="btn btn-success" onclick="handle_edit_template_step({{ step.id }},{{ step.template.id }},false,this,false);return false;">
					<i class="icon-share-alt icon-white"></i>
					返回
				</button>
			</div>
		</div>
	</form>
</div>

ujobs/source/ujobs/templates/md_manage/md_view.html
<!-- 查看模板 -->          
<div class="row-fluid">
	<form id="myform" action="javascript:void(0);" method="post" class="form-horizontal myform">{% csrf_token %}
		<div class="alert alert-warning">模板中步骤增删、顺序调整、步骤名称、文本步骤描述以及脚本替换会同步到实例中。同一脚本不同版本的变化不会同步到实例中。
			<a class="tooltips" href="javascript:void(0);" data-toggle="tooltip" data-placement="right" title="同步功能会将作业模板中的如下数据同步至已有作业实例中：作业模板中步骤的个数、顺序、名称、文本步骤内容等。    对于分发文件和拉取文件步骤，不会同步详细设置，允许每个作业实例中的分发文件和拉取文件与作业模板不一致。"><i class="icon-question-sign"></i></a>	
		</div>
		<div class="control-group">
			<label class="control-label muted">模板名称：</label>
			<span class="control-label txt-ellipsis" style="text-align:left;">{{ template.name }}</span>
			<label class="control-label muted">开发商：</label>
			<span class="control-label" style="text-align:left;">{{ template.create_user.username }}</span>
			<div class="controls pull-right" style="margin-right:128px;">
				<button type="button" class="btn btn-info" onclick="template_edit('{{ template.id }}');">
                    <i class="icon-edit icon-white"></i>
                    编辑作业模板
                </button>
				<button type="button" class="btn btn-info" onclick="template_del('{{ template.id }}');">
                    <i class="icon-trash icon-white"></i>
                    删除作业模板
                </button>
			</div>				  		  
		</div>
		<div class="control-group">
			<label class="control-label muted">模板类型：</label>
			<span class="control-label" style="text-align:left;">{{ template.get_template_type_display }}</span>
			<label class="control-label muted">所属业务：</label>
			<span class="control-label" style="text-align:left;">{{ template.work_type|default_if_none:'' }}</span>
		</div>
		<div class="control-group">
            <label class="control-label muted">更新时间：</label>
			<span class="control-label" style="text-align:left;">{{ template.updated|date:'Y-m-d H:i:s' }}</span>
			<label class="control-label muted">备注：</label>
			<span class="control-label limit-size">{{ template.remarks }}</span>
		</div>
		<div class="control-group">
			<div class="controls pull-right">
				<button type="button" onclick="javascript:example_manage_add({{ template.id }})" class="btn btn-info reset">
                    <i class="icon-plus icon-white"></i>
                    添加作业实例
                </button>	
				<button type="button" onclick="javascript:template_job_sync({{ template.id }})" class="btn btn-success">
                    <i class="icon-repeat icon-white"></i>
                    同步作业实例
                </button>	       
				<button type="button" id="refresh_job_list_{{ template.id }}" class="btn btn-success reset">
                    <i class="icon-refresh icon-white"></i>
                    刷新作业实例
                </button>
			</div>
		</div>
		<table  class="table table-striped table-bordered table-hover" id="md_example_{{ template.id }}">
			  <thead>
				<tr>
				  <th width=2% class="text-center"><input class="md_view_checked_all_{{ template.id }}" value="" type="checkbox"></th>
				  <th>实例名称</th>
				  <th>创建时间</th>
				  <th>创建人</th>
				  <th>状态</th>
				  <th>操作</th>
				</tr>
			  </thead>
			  <tbody>

			  </tbody>
		</table>
	</form>
</div>
<script>
$(function () {
    var job_list_{{ template.id }} = null;
    
	job_list_{{ template.id }} = $("#md_example_{{ template.id }}").dataTable({
	 "sDom": 'lfrtip',
	 "bLengthChange":false,
	 "iDisplayLength":10,
	 "aoColumnDefs": [{ "bSortable": false, "aTargets": [0,5] }],
	 "bProcessing": true,
	 "bServerSide": true,
	 "sPaginationType": "full_numbers",
	 "sAjaxSource": "{{ajax_url}}",
	 "bFilter":false,
	 "oLanguage":{
	 	   "sUrl":'/static/tool_js/data_table/cn/jquery.dataTable.cn.txt'
	         }
	 });
	 
	 $(".tooltips").tooltip();
	 
	// 全选全不选
	var md_view_checked_all=".md_view_checked_all_{{ template.id }}";
	var md_view_checked_it=".md_view_checked_it_{{ template.id }}";
	check_all(md_view_checked_all,md_view_checked_it);

    // bind click action.
    $('#refresh_job_list_{{ template.id }}').bind('click', function () {
        job_list_{{ template.id }}.fnReloadAjax("{{ ajax_url }}");
        $(".md_view_checked_all_{{ template.id }}").prop("checked",false);
        jSuccess("实例列表刷新成功");
    });
});

    // 同步作业实例
    function template_job_sync(template_id){
        if($(".md_view_checked_it_{{ template.id }}").filter(":checked").length==0) {
            jNotify("指定实例列表为空，同步实例失败！");
            return false;
        }
        else{
            var check_list = [];  

            $('#md_example_{{ template.id }} input:checked').each(function (){  
                check_list.push($(this).val());
            });
            $.ajax({
                type: 'post',
                url: '/job/template_job_sync/',
                data: {
                        'template_id':template_id,
                        'check_list':check_list
                      },
                dataType: 'json',
                success: function (data){
                    if(data.status==500){
                        jError('同步作业实例失败!');
                    }else{
                        jSuccess('同步作业实例成功!');
                    }

                    job_list_{{ template.id }}.fnReloadAjax("{{ ajax_url }}");
                    $(".md_view_checked_all_{{ template.id }}").prop("checked",false);
                },
                error: function (re, status){
                }
            });
            
            return false;
        }
    }
</script>

ujobs/source/ujobs/templates/md_manage/new_md.html
<!-- 新建作业模板 -->
<div class="row-fluid">
	<form id="new_template_form_{{ check_id }}" class="form-horizontal" action="javascript:void(0);" method="POST">{% csrf_token %}
		<div class="control-group">
			<label class="control-label muted">模板名称：<span class="red">*</span></label>
			<div class="controls">
                {{ templateForm.name }}
                <span style="display: inline-block;color:#999">{{templateForm.name.errors}}</span>
                <span class="help-block"></span>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label muted">模板类型：<span>&nbsp;&nbsp;</span></label>
			<div class="controls">
                {{ templateForm.template_type }}
                <span style="display: inline-block;color:#999">{{templateForm.template_type.errors}}</span>
                <span class="help-block"></span>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label muted">所属业务：<span>&nbsp;&nbsp;</span></label>
			<div class="controls">
  				<select style="width:435px;" id="work_type" class="work-type" name="work_type">
  					<option value="" selected>未分类</option>
  				</select>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label muted">模板备注：<span class="red">*</span></label>
			<div class="controls">
                {{ templateForm.remarks }}
                <span style="display: inline-block;color:#999">{{templateForm.remarks.errors}}</span>
                <span class="help-block"></span>
			</div>
		</div>
        <input type="hidden" id="check_id" name="check_id" value="{{ check_id }}">
		<div class="control-group">
			<div class="controls">
				<button class="btn btn-primary" onclick="submit_create_new_template({{ check_id }});">
                    <i class="icon-ok icon-white"></i>
                    创建模板
                </button>
			</div>
		</div>
	</form>
</div>

<script>
    // 所属业务拉取
    var e=$(".work-type");
    product_from(e,'sss')
</script>